 <nav class="navbar navbar-expand-lg navbar-dark">
            <div class="container">
                <a class="navbar-brand" href="index.php">
                    <img src="assets/images/SkillSwap_logo.png" alt="SkillSwap Logo" class="img-fluid" />
                </a>
                <div class="collapse navbar-collapse">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item"><a class="nav-link" href="index.php">Home</a></li>
                        <li class="nav-item"><a class="nav-link" href="skills.php">All Skills</a></li>
                        <li class="nav-item"><a class="nav-link" href="gallery.php">Gallery</a></li>
                        <li class="nav-item"><a class="nav-link" href="add.php">Add Skill</a></li>
                    </ul>
                    <form class="d-flex search-form">
                        <div class="search-field">
                            <span class="material-icons">search</span>

                            <input class="form-control" type="search" placeholder="Search skills..."
                                aria-label="Search" />
                        </div>
                    </form>
                </div>
            </div>
        </nav>